# Generated by Django 6.0.4 on 2026-04-27 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_slug', models.CharField(max_length=80)),
                ('pack_title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('blocked', 'Bloqueado'), ('fulfilled', 'Entregue'), ('refunded', 'Reembolsado')], default='pending', max_length=20)),
                ('amount_cents', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='brl', max_length=8)),
                ('stripe_session_id', models.CharField(blank=True, max_length=120)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=120)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('purchaser_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('risk_score', models.PositiveIntegerField(default=0)),
                ('risk_reasons', models.JSONField(blank=True, default=list)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('delivery_bundle_path', models.CharField(blank=True, max_length=500)),
                ('delivery_checksum', models.CharField(blank=True, max_length=64)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80)),
                ('severity', models.CharField(default='info', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.catalogorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
